### ISSUE TITLE
ABOUT 'def findHiddenTopics'

### ISSUE THREAD

**Issue by wjmzjx** [HongyuGong/Document-Similarity-via-Hidden-Topics#1]
I find out that you select hidden topics from V instead of U in codes, which is contrary to derivation. 
Could  you explain it ?

**Comment by HongyuGong** [comment]
Hello, thanks for your interest. They are actually equivalent. In the paper, the long doc matrix W is a (dxN) matrix where each column is a d-dimension vector. In the implementation, the variable of long doc matrix (denoted as W_{c} for simplicity) is an (Nxd) matrix, i.e., the transpose of W. 
According to SVD, we know that W = U\Sigma V{T}, and W_{c}=U_{c}\Sigma V_{c}^{T}. Since W_{c} is the transpose of W, we also have W_{c}=V\Sigma U^{T}. Now we can find the equivalence:
U_{c} = V, and V_{c} = U.
There is why the implementation uses V as hidden topics.
